version: '3.9'

services:
  # --- Zookeeper ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # --- Kafka Broker ---
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "29092:9092"  # Evita conflito de porta no host
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # --- Aplicação principal (NestJS API) ---
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamforge_api
    ports:
      - "3000:3000"
    depends_on:
      - kafka
    environment:
      NODE_ENV: production
      DATABASE_URL: "mongodb+srv://Businesswithcocky:sIY%244HQ%253Ew0R%295Der%255E8bX@clusterone.qca1oap.mongodb.net/StreamForge?retryWrites=true&w=majority"
      CLOUDINARY_CLOUD_NAME: "dwp3wuum6"
      CLOUDINARY_API_KEY: "197286731484726"
      CLOUDINARY_API_SECRET: "Ygo6whjXErJn6htPmiPQr8iHN-o"
      CLOUDINARY_URL: "cloudinary://197286731484726:Ygo6whjXErJn6htPmiPQr8iHN-o@dwp3wuum6"
      KAFKA_BROKER: "kafka:9092"  # DNS interno do Docker
      JWT_SECRET: "streamforge_secret_key"
      PORT: 3000
    command: npm run start:prod
    volumes:
      - .:/app
      - /app/node_modules

  # --- Worker (processamento de vídeos) ---
  video-processor:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: streamforge_video_worker
    restart: always
    depends_on:
      - kafka
    environment:
      DATABASE_URL: "mongodb+srv://Businesswithcocky:sIY%244HQ%253Ew0R%295Der%255E8bX@clusterone.qca1oap.mongodb.net/StreamForge?retryWrites=true&w=majority"
      CLOUDINARY_URL: "cloudinary://197286731484726:Ygo6whjXErJn6htPmiPQr8iHN-o@dwp3wuum6"
      KAFKA_BROKER: "kafka:9092"
      JWT_SECRET: "streamforge_secret_key"
    command: npm run worker


